version 2:

sources:
  - name: raw
    database: lego_catalog
    schema: raw

    tables:
      - name: themes
      - name: colors
      - name: part_categories
      - name: parts
      - name: part_relationships
      - name: elements
      - name: sets
      - name: minifigs
      - name: inventories
      - name: inventory_parts
      - name: inventory_sets
      - name: inventory_minifigs